import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  images: {
    remotePatterns: [
      { protocol: "https", hostname: "napkinsdev.s3.us-east-1.amazonaws.com" },
      { protocol: "https", hostname: "my-1st-aws-bucket-for-files-storage.s3.eu-north-1.amazonaws.com" },
      { protocol: "https", hostname: "cdn.prod.website-files.com" },
      { protocol: "https", hostname: "api.together.ai" },
      { protocol: "https", hostname: "fal.media" },
    ],
  },

  async redirects() {
    const oldPaths: string[] = [
      "/photo-editors/",
      "/photo-effects/",
      "/photo-filters/",
      "/collage-makers/",
      "/photo-frames/",
      "/webcams/",
      "/upload/",
      "/aviary/",
      "/befunky/",
      "/cameroid/",
      "/canva/",
      "/.comicwebcam/",
      "/enjoypic/",
      "/fotoflexer/",
      "/fotor/",
      "/fotostars/",
      "/funphotobox/",
      "/gimp/",
      "/hipstertool/",
      "/imagechef/",
      "/ipiccy/",
      "/loonapix/",
      "/lunapic/",
      "/paint-net/",
      "/phixr/",
      "/pho-to/",
      "/photoshop-express/",
      "/photovisi/",
      "/picadilo/",
      "/picfull/",
      "/picjoke/",
      "/picmonkey/",
      "/picnik/",
      "/pixect/",
      "/pixer/",
      "/pixlr-editor/",
      "/pixlr-express/",
      "/pixlr-o-matic/",
      "/pizap/",
      "/psykopaint/",
      "/retrica/",
      "/ribbet/",
      "/rollip/",
      "/seenly/",
      "/sketchpad/",
      "/splashup/",
      "/sumopaint/",
      "/webcamtoy/",
      "/ua/",
      "/ua/photo-editors/",
      "/ua/photo-effects/",
      "/ua/photo-filters/",
      "/ua/collage-makers/",
      "/ua/photo-frames/",
      "/ua/webcams/",
      "/ua/upload/",
      "/ua/aviary/",
      "/ua/befunky/",
      "/ua/cameroid/",
      "/ua/canva/",
      "/ua/comicwebcam/",
      "/ua/enjoypic/",
      "/ua/fotoflexer/",
      "/ua/fotor/",
      "/ua/fotostars/",
      "/ua/funphotobox/",
      "/ua/gimp/",
      "/ua/hipstertool/",
      "/ua/imagechef/",
      "/ua/ipiccy/",
      "/ua/loonapix/",
      "/ua/lunapic/",
      "/ua/paint-net/",
      "/ua/phixr/",
      "/ua/pho-to/",
      "/ua/photoshop-express/",
      "/ua/photovisi/",
      "/ua/picadilo/",
      "/ua/picfull/",
      "/ua/picjoke/",
      "/ua/picmonkey/",
      "/ua/picnik/",
      "/ua/pixect/",
      "/ua/pixer/",
      "/ua/pixlr-editor/",
      "/ua/pixlr-express/",
      "/ua/pixlr-o-matic/",
      "/ua/pizap/",
      "/ua/psykopaint/",
      "/ua/retrica/",
      "/ua/ribbet/",
      "/ua/rollip/",
      "/ua/seenly/",
      "/ua/sketchpad/",
      "/ua/splashup/",
      "/ua/sumopaint/",
      "/ua/webcamtoy/",
      "/ru/",
      "/ru/photo-editors/",
      "/ru/photo-effects/",
      "/ru/photo-filters/",
      "/ru/collage-makers/",
      "/ru/photo-frames/",
      "/ru/webcams/",
      "/ru/upload/",
      "/ru/aviary/",
      "/ru/befunky/",
      "/ru/cameroid/",
      "/ru/canva/",
      "/ru/comicwebcam/",
      "/ru/enjoypic/",
      "/ru/fotoflexer/",
      "/ru/fotor/",
      "/ru/fotostars/",
      "/ru/funphotobox/",
      "/ru/gimp/",
      "/ru/hipstertool/",
      "/ru/imagechef/",
      "/ru/ipiccy/",
      "/ru/loonapix/",
      "/ru/lunapic/",
      "/ru/paint-net/",
      "/ru/phixr/",
      "/ru/pho-to/",
      "/ru/photoshop-express/",
      "/ru/photovisi/",
      "/ru/picadilo/",
      "/ru/picfull/",
      "/ru/picjoke/",
      "/ru/picmonkey/",
      "/ru/picnik/",
      "/ru/pixect/",
      "/ru/pixer/",
      "/ru/pixlr-editor/",
      "/ru/pixlr-express/",
      "/ru/pixlr-o-matic/",
      "/ru/pizap/",
      "/ru/psykopaint/",
      "/ru/retrica/",
      "/ru/ribbet/",
      "/ru/rollip/",
      "/ru/seenly/",
      "/ru/sketchpad/",
      "/ru/splashup/",
      "/ru/sumopaint/",
      "/ru/webcamtoy/",
    ];

    // Повертаємо обидві версії шляху: з трейлінг-слешем і без
    const sources = oldPaths.flatMap((p) => {
      const withoutSlash = p.replace(/\/$/, "");
      return [p, withoutSlash];
    });

    return sources.map((source) => ({
      source,
      destination: "/",
      permanent: true,
    }));
  },
};

export default nextConfig;